#! /bin/bash

#//1) Moltiplicazione tra 432 per 5.6
#   echo "$(echo '432 * 5.6' | bc)"

#2) i=43.2 j=1.5 ; divisione tra 'i' e 'j', risultato nella variabile 'k'

#i=43.2 && j=1.5 && k=
#echo $i : $j = $k

#3) divisone tra 142  e 13, mettere nella variabile 'l' il RESTO della divisione

#x=142 && y=13
#echo $x : $y = $z con il resto di $l

#//4) Quadrato di 'k'
#   k=5 && ((k2=k**2))
#   echo $k2

#5) Convertire 1245 in binario


#6) Convertire 1245 in ottale
#n=1245
#o=n/8
#x=n/o and %
#y=%/8 and %%
#z=%%/8 and 0
#then the octal is xyz


#7) Incrementare l, dopo averlo moltiplicato per 3, e aver salvato il risultato nella variabile 'pippo'

#   [[test]]

#//8) verificare se viene prima "vero" o "falso", alfabeticamente
#[[ 'falso' > 'vero' ]] ; echo $?

#9) verificare se 5 è minore di 'l'

#//10) verificare viene prima "VERO" o "falso", alfabeticamente
#[[ 'falso' > 'VERO' ]] ; echo $?


#11)salvare nelle variabili 'nome1', 'nome2' i nomi di due membri di questo corso
#M=Michele
#F=Federico
#12) controllare se hanno la stessa lettera iniziale

#13) controllare se hanno la stessa lettera finale

